services:
  api:
    build:
      context: .
      dockerfile: StatsHub_Api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - postgres
    networks:
      - stats_hub_network

  web:
    build:
      context: .
      dockerfile: StatsHub_Web/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - api
    networks:
      - stats_hub_network

  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=stats_hub
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - stats_hub_network

networks:
  stats_hub_network:
    driver: bridge

volumes:
  postgres-data: